# Generated by Django 3.0.7 on 2020-06-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_ip_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
