# Generated by Django 3.0.6 on 2020-05-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200527_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='stripe_card_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
