# Generated by Django 3.0.6 on 2020-05-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_member_stripe_card_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='stripe_card_number',
            new_name='stripe_card_token',
        ),
        migrations.AddField(
            model_name='member',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
