# Generated by Django 3.0.6 on 2020-05-13 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_date', models.DateField(auto_now_add=True)),
                ('inv_number', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('draft', 'Draft'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('inv_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.Invoice')),
            ],
        ),
    ]
