# Generated by Django 3.0.6 on 2020-05-17 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0001_initial'),
        ('invoice_app', '0002_invoice_inv_receiving_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('records_count', models.IntegerField()),
                ('stripe_token', models.CharField(blank=True, max_length=100, null=True)),
                ('member_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_handler.MemberData')),
            ],
        ),
    ]
