# Generated by Django 3.0.6 on 2020-05-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0002_auto_20200526_1419'),
        ('invoice_app', '0003_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='member_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_handler.MemberDataFile'),
        ),
    ]
