# Generated by Django 3.0.6 on 2020-05-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('membership_type', models.CharField(blank=True, choices=[('starter', 'Starter'), ('professional', 'Professional'), ('expert', 'Expert')], max_length=20, null=True)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yearly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stripe_plane_id', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_fee_per_extra_record', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=60, null=True)),
                ('active', models.BooleanField()),
                ('sub_range', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, null=True)),
                ('subscription_start_date', models.DateField(blank=True, null=True)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
