# Generated by Django 3.0.7 on 2020-06-25 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_handler', '0002_auto_20200625_1341'),
        ('membership', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_membership', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stripe_member_id', models.CharField(max_length=50)),
                ('data_file_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_file', to='data_handler.DataFile')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='membership.Membership')),
                ('subscription_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_obj', to='membership.Subscription')),
            ],
            options={
                'db_table': 'user_membership',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
