# Generated by Django 3.0.6 on 2020-05-27 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('membership', '0001_initial'),
        ('data_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='member', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stripe_member_id', models.CharField(max_length=50)),
                ('data_file_obj', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_file', to='data_handler.DataFile')),
                ('membership', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='membership.Membership')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='user_membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='membership.UserMembership'),
        ),
    ]
