# Generated by Django 3.0.6 on 2020-05-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20200527_1602'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermembership',
            table='user_membership',
        ),
    ]
