# Generated by Django 3.0.8 on 2020-08-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_remove_membership_allowed_records_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_allowed_records_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
