# Generated by Django 3.0.6 on 2020-05-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20200527_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='additional_fee_per_extra_record',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
