# Generated by Django 3.0.8 on 2020-08-02 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0021_auto_20200802_0819'),
        ('membership', '0005_auto_20200801_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='data_handler_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_handler_session', to='data_handler.DataHandlerSession'),
        ),
    ]
