# Generated by Django 3.0.6 on 2020-05-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_auto_20200528_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='all_records_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
