# Generated by Django 3.1.1 on 2020-09-29 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_subscription_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_plan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.membership'),
        ),
    ]
