# Generated by Django 3.0.6 on 2020-05-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_membership_all_records_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='all_records_count',
            new_name='allowed_records_count',
        ),
    ]
