# Generated by Django 3.0.6 on 2020-05-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0001_initial'),
        ('membership', '0010_auto_20200528_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='data_file_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_file', to='data_handler.DataFile'),
        ),
    ]
