# Generated by Django 3.1.3 on 2020-11-21 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0013_auto_20201121_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
