# Generated by Django 3.0.6 on 2020-05-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='id',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='slug',
            field=models.SlugField(default='company', primary_key=True, serialize=False, unique=True),
        ),
    ]
