# Generated by Django 3.0.7 on 2020-06-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload_procedure', models.CharField(blank=True, choices=[('local_file', 'Local File'), ('google_plus', 'Google Plus'), ('one_drive', 'One Drive'), ('dropbox', 'Dropbox'), ('none', 'None')], max_length=20, null=True)),
                ('data_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('all_records_count', models.BigIntegerField(blank=True, null=True)),
                ('allowed_records_count', models.IntegerField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('selected_columns', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member_data_files',
            },
        ),
        migrations.CreateModel(
            name='MemberDownloadCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accept_terms', models.BooleanField(blank=True, default=False, null=True)),
                ('is_download_template', models.BooleanField(blank=True, default=False, null=True)),
                ('download_counter', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'members_download_counter',
            },
        ),
    ]
