# Generated by Django 3.0.6 on 2020-05-17 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0002_auto_20200513_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file_path', models.FileField(blank=True, null=True, upload_to='members_data/%Y/%m/%d/')),
                ('all_records_count', models.BigIntegerField(blank=True, null=True)),
                ('allowed_records_count', models.IntegerField(blank=True, null=True)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.UserMembership')),
            ],
        ),
    ]
