# Generated by Django 3.0.6 on 2020-05-28 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_data_file', to=settings.AUTH_USER_MODEL),
        ),
    ]
