# Generated by Django 3.0.6 on 2020-05-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload_procedure', models.CharField(blank=True, choices=[('local_file', 'Local File'), ('google_plus', 'Google Plus'), ('one_drive', 'One Drive'), ('dropbox', 'Dropbox')], max_length=20, null=True)),
                ('data_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('all_records_count', models.BigIntegerField(blank=True, null=True)),
                ('allowed_records_count', models.IntegerField(blank=True, null=True)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='memberdata',
            name='member',
        ),
    ]
