# Generated by Django 3.0.6 on 2020-05-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0002_datafile_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='selected_columns',
            field=models.TextField(blank=True, null=True),
        ),
    ]
