# Generated by Django 3.0.7 on 2020-06-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0002_auto_20200625_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdownloadcounter',
            name='is_accept_download_template',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
