# Generated by Django 3.0.6 on 2020-05-26 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20200513_2026'),
        ('data_handler', '0003_auto_20200526_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdatafile',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_data_file', to='membership.UserMembership'),
        ),
    ]
