# Generated by Django 3.0.6 on 2020-05-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0004_auto_20200526_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberdatafile',
            options={'verbose_name': 'member_data_file'},
        ),
    ]
