# Generated by Django 3.0.6 on 2020-05-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0005_auto_20200526_1718'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='memberdatafile',
            table='member_data_file',
        ),
    ]
