# Generated by Django 3.0.6 on 2020-05-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0006_auto_20200526_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberdatafile',
            old_name='member',
            new_name='membership',
        ),
    ]
