# Generated by Django 3.0.8 on 2020-07-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0008_auto_20200702_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='all_columns_with_dtypes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
