# Generated by Django 3.0.8 on 2020-07-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0009_datafile_all_columns_with_dtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='is_process_complete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
