# Generated by Django 3.0.8 on 2020-07-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0010_datafile_is_process_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='is_process_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
