# Generated by Django 3.0.8 on 2020-07-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0011_auto_20200708_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='current_session_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='data_handler_session_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
