# Generated by Django 3.0.8 on 2020-07-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0012_auto_20200718_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='current_session_name',
            field=models.CharField(blank=True, choices=[('upload', 'Upload'), ('pick_columns', 'Pick Columns'), ('data_process', 'Data Processing'), ('run_modal', 'Run Predictive Modal')], max_length=70, null=True),
        ),
    ]
