# Generated by Django 3.0.8 on 2020-07-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0013_auto_20200718_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='data_handler_session_name',
            new_name='data_handler_session_label',
        ),
    ]
