# Generated by Django 3.0.8 on 2020-07-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0014_auto_20200718_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdownloadcounter',
            name='date_inserted',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
