# Generated by Django 3.0.8 on 2020-07-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0016_datafile_current_session_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='current_session_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
