# Generated by Django 3.0.8 on 2020-07-31 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0017_auto_20200731_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='current_session_date_time',
            new_name='session_date_time',
        ),
    ]
