# Generated by Django 3.0.8 on 2020-08-01 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0018_auto_20200731_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='session_date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
