# Generated by Django 3.0.8 on 2020-08-02 08:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0019_auto_20200801_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='current_session_name',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='session_date_time',
        ),
        migrations.CreateModel(
            name='DataHandlerSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_session_name', models.CharField(blank=True, choices=[('upload', 'Upload'), ('pick_columns', 'Pick Columns'), ('data_process', 'Data Processing'), ('run_modal', 'Run Predictive Modal')], max_length=70, null=True)),
                ('session_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('data_handler_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_handler.DataFile')),
            ],
        ),
    ]
