# Generated by Django 3.0.8 on 2020-08-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0020_auto_20200802_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahandlersession',
            name='session_date_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
