# Generated by Django 3.0.8 on 2020-08-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0021_auto_20200802_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='data_handler_session_label',
        ),
        migrations.AddField(
            model_name='datahandlersession',
            name='data_handler_session_label',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='datahandlersession',
            name='session_date_time',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
