# Generated by Django 3.0.8 on 2020-08-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0022_auto_20200802_0915'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datahandlersession',
            table='data_handler_sessions',
        ),
    ]
