# Generated by Django 3.0.8 on 2020-08-02 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0023_auto_20200802_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahandlersession',
            name='data_handler_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sessions', to='data_handler.DataFile'),
        ),
    ]
