# Generated by Django 3.0.8 on 2020-08-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0026_auto_20200802_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='datafile',
            name='has_sessions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datahandlersession',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
