# Generated by Django 3.0.9 on 2020-08-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0027_auto_20200802_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahandlersession',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
