# Generated by Django 3.0.9 on 2020-08-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0031_auto_20200804_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='last_uploaded_session',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
