# Generated by Django 3.1.3 on 2020-11-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0032_datafile_last_uploaded_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='is_run_the_model',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
