# Generated by Django 3.1.3 on 2020-11-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0033_datafile_is_run_the_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahandlersession',
            name='base_data_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
