# Generated by Django 3.1.3 on 2020-11-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0034_datahandlersession_base_data_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahandlersession',
            name='donation_columns',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
